Added basic curses UI.
git-svn-id: svn://svn.code.sf.net/p/directnet/code/trunk/directnet@57 40aaf297-f90e-0410-8da6-8adc2782f1e2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB build build_cpu build_vendor build_os host host_cpu host_vendor host_os acx_pthread_config PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS WX_CONFIG_PATH WX_CPPFLAGS WX_CFLAGS WX_CXXFLAGS WX_CFLAGS_ONLY WX_CXXFLAGS_ONLY WX_LIBS WX_LIBS_STATIC WX_VERSION UI_CFLAGS UI_CPPFLAGS UI_CXXFLAGS UI_LIBS UI_LDFLAGS UI_DIR UI_DUMB_TRUE UI_DUMB_FALSE CPP EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB build build_cpu build_vendor build_os host host_cpu host_vendor host_os acx_pthread_config PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS WX_CONFIG_PATH WX_CPPFLAGS WX_CFLAGS WX_CXXFLAGS WX_CFLAGS_ONLY WX_CXXFLAGS_ONLY WX_LIBS WX_LIBS_STATIC WX_VERSION CURSES_LIBS CURSES_INCLUDEDIR CPP EGREP UI_CFLAGS UI_CPPFLAGS UI_CXXFLAGS UI_LIBS UI_LDFLAGS UI_DIR UI_DUMB_TRUE UI_DUMB_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -872,6 +872,11 @@ Optional Packages:
   --with-wx-prefix=PREFIX   Prefix where wxWindows is installed (optional)
   --with-wx-exec-prefix=PREFIX Exec prefix where wxWindows is installed (optional)
   --with-wx-config=CONFIG   wx-config script to use (optional)
+  --with-sco              Use this to turn on SCO-specific code
+  --with-sunos-curses     Used to force SunOS 4.x curses
+  --with-osf1-curses      Used to force OSF/1 curses
+  --with-vcurses=incdir Used to force SysV curses
+  --with-ncurses=dir  Compile with ncurses/locate base dir
 
 Some influential environment variables:
   CC          C compiler command
@@ -1774,7 +1779,7 @@ am__tar='${AMTAR} chof - "$$tardir"'; am__untar='${AMTAR} xf -'
           ac_config_headers="$ac_config_headers config.h"
 
 
-                                        ac_config_files="$ac_config_files Makefile src/Makefile src/ui-dumb/Makefile src/ui-wx/Makefile"
+                                                  ac_config_files="$ac_config_files Makefile src/Makefile src/ui-curses/Makefile src/ui-dumb/Makefile src/ui-wx/Makefile"
 
 
 # Checks for programs.
@@ -3980,6 +3985,62 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+
+cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define NCURSES_970530
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define NO_COLOR_CURSES
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define SCO_FLAVOR
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_NCURSES
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_SUNOS_CURSES
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_SYSV_CURSES
+_ACEOF
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 # Figure out what UI to use
 # Check whether --enable-ui or --disable-ui was given.
 if test "${enable_ui+set}" = set; then
@@ -3987,6 +4048,7 @@ if test "${enable_ui+set}" = set; then
   case "$enableval" in
         dumb) ui=dumb ;;
         wx) ui=wx ;;
+        curses) ui=curses ;;
 esac
 else
   ui=determine
@@ -4007,6 +4069,8 @@ then
         UI_DIR=ui-dumb
         found_ui=yes
         ui=dumb
+        { echo "$as_me:$LINENO: Using dumb UI" >&5
+echo "$as_me: Using dumb UI" >&6;}
 fi
 
 if test "x$ui" = "xwx" || ( test "x$ui" = "xdetermine" && test "x$found_ui" = "xno" )
@@ -4217,6 +4281,7 @@ echo "${ECHO_T}no (version $WX_VERSION is not new enough)" >&6
 
 
 
+
         if test "x$wxWin" != x1
         then
                 if test "x$ui" = "xwx"
@@ -4240,36 +4305,14 @@ The wx-config script could not be found.
                 UI_DIR=ui-wx
                 found_ui=yes
                 ui=wx
+                { echo "$as_me:$LINENO: Using wx UI" >&5
+echo "$as_me: Using wx UI" >&6;}
         fi
 fi
 
-if test "x$found_ui" = "xno"
+if test "x$ui" = "xcurses" || ( test "x$ui" = "xdetermine" && test "x$found_ui" = "no" )
 then
-        { { echo "$as_me:$LINENO: error: Couldn't find a working UI." >&5
-echo "$as_me: error: Couldn't find a working UI." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
-
-
-
-
-
-
-
-if test "x$ui" = "xdumb"; then
-  UI_DUMB_TRUE=
-  UI_DUMB_FALSE='#'
-else
-  UI_DUMB_TRUE='#'
-  UI_DUMB_FALSE=
-fi
-
-
-
-# Checks for header files.
-ac_ext=c
+        ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
@@ -4519,6 +4562,498 @@ echo "${ECHO_T}$ac_cv_prog_egrep" >&6
  EGREP=$ac_cv_prog_egrep
 
 
+
+	search_ncurses=true
+	screen_manager=""
+	has_curses=false
+
+	CFLAGS=${CFLAGS--O}
+
+
+
+
+
+# Check whether --with-sco or --without-sco was given.
+if test "${with_sco+set}" = set; then
+  withval="$with_sco"
+
+	  if test x$withval = xyes; then
+		cat >>confdefs.h <<\_ACEOF
+#define SCO_FLAVOR 1
+_ACEOF
+
+		CFLAGS="$CFLAGS -D_SVID3"
+	  fi
+
+fi;
+
+
+# Check whether --with-sunos-curses or --without-sunos-curses was given.
+if test "${with_sunos_curses+set}" = set; then
+  withval="$with_sunos_curses"
+
+	  if test x$withval = xyes; then
+
+	search_ncurses=false
+	screen_manager="SunOS 4.x /usr/5include curses"
+	echo "$as_me:$LINENO: result: Using SunOS 4.x /usr/5include curses" >&5
+echo "${ECHO_T}Using SunOS 4.x /usr/5include curses" >&6
+	cat >>confdefs.h <<\_ACEOF
+#define USE_SUNOS_CURSES 1
+_ACEOF
+
+	cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+	has_curses=true
+	cat >>confdefs.h <<\_ACEOF
+#define NO_COLOR_CURSES 1
+_ACEOF
+
+	cat >>confdefs.h <<\_ACEOF
+#define USE_SYSV_CURSES 1
+_ACEOF
+
+	CURSES_INCLUDEDIR="-I/usr/5include"
+	CURSES_LIBS="/usr/5lib/libcurses.a /usr/5lib/libtermcap.a"
+	echo "$as_me:$LINENO: result: Please note that some screen refreshs may fail" >&5
+echo "${ECHO_T}Please note that some screen refreshs may fail" >&6
+
+	  fi
+
+fi;
+
+
+# Check whether --with-osf1-curses or --without-osf1-curses was given.
+if test "${with_osf1_curses+set}" = set; then
+  withval="$with_osf1_curses"
+
+	  if test x$withval = xyes; then
+
+       echo "$as_me:$LINENO: result: Using OSF1 curses" >&5
+echo "${ECHO_T}Using OSF1 curses" >&6
+       search_ncurses=false
+       screen_manager="OSF1 curses"
+       cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+       has_curses=true
+       cat >>confdefs.h <<\_ACEOF
+#define NO_COLOR_CURSES 1
+_ACEOF
+
+       cat >>confdefs.h <<\_ACEOF
+#define USE_SYSV_CURSES 1
+_ACEOF
+
+       CURSES_LIBS="-lcurses"
+
+	  fi
+
+fi;
+
+
+# Check whether --with-vcurses or --without-vcurses was given.
+if test "${with_vcurses+set}" = set; then
+  withval="$with_vcurses"
+  if test x$withval != xyes; then
+		CURSES_INCLUDEDIR="-I$withval"
+	  fi
+
+	echo "$as_me:$LINENO: result: Using SysV curses" >&5
+echo "${ECHO_T}Using SysV curses" >&6
+	cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+	has_curses=true
+	cat >>confdefs.h <<\_ACEOF
+#define USE_SYSV_CURSES 1
+_ACEOF
+
+	search_ncurses=false
+	screen_manager="SysV/curses"
+	CURSES_LIBS="-lcurses"
+
+
+fi;
+
+
+# Check whether --with-ncurses or --without-ncurses was given.
+if test "${with_ncurses+set}" = set; then
+  withval="$with_ncurses"
+  if test x$withval = xno ; then
+		search_ncurses=false
+	  elif test x$withval != xyes ; then
+		CURSES_LIBS="$LIBS -L$withval/lib -lncurses"
+		CURSES_INCLUDEDIR="-I$withval/include"
+		search_ncurses=false
+		screen_manager="ncurses"
+		cat >>confdefs.h <<\_ACEOF
+#define USE_NCURSES 1
+_ACEOF
+
+		cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+		has_curses=true
+	  fi
+
+fi;
+
+	if $search_ncurses
+	then
+
+    { echo "$as_me:$LINENO: checking \"location of ncurses.h file\"..." >&5
+echo "$as_me: checking \"location of ncurses.h file\"..." >&6;}
+
+
+    if $search_ncurses
+    then
+        if test -f /usr/include/ncurses.h
+	then
+	    echo "$as_me:$LINENO: result: Found ncurses on /usr/include/ncurses.h" >&5
+echo "${ECHO_T}Found ncurses on /usr/include/ncurses.h" >&6
+ 	    CURSES_LIBS="-lncurses"
+	    CURSES_INCLUDEDIR=""
+	    search_ncurses=false
+	    screen_manager="ncurses on /usr/include"
+            cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+            has_curses=true
+	    cat >>confdefs.h <<\_ACEOF
+#define USE_NCURSES 1
+_ACEOF
+
+	fi
+    fi
+
+
+    if $search_ncurses
+    then
+        if test -f /usr/include/ncurses/ncurses.h
+	then
+	    echo "$as_me:$LINENO: result: Found ncurses on /usr/include/ncurses/ncurses.h" >&5
+echo "${ECHO_T}Found ncurses on /usr/include/ncurses/ncurses.h" >&6
+ 	    CURSES_LIBS="-lncurses"
+	    CURSES_INCLUDEDIR="-I/usr/include/ncurses"
+	    search_ncurses=false
+	    screen_manager="ncurses on /usr/include/ncurses"
+            cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+            has_curses=true
+	    cat >>confdefs.h <<\_ACEOF
+#define USE_NCURSES 1
+_ACEOF
+
+	fi
+    fi
+
+
+    if $search_ncurses
+    then
+        if test -f /usr/local/include/ncurses.h
+	then
+	    echo "$as_me:$LINENO: result: Found ncurses on /usr/local/include/ncurses.h" >&5
+echo "${ECHO_T}Found ncurses on /usr/local/include/ncurses.h" >&6
+ 	    CURSES_LIBS="-L/usr/local/lib -lncurses"
+	    CURSES_INCLUDEDIR="-I/usr/local/include"
+	    search_ncurses=false
+	    screen_manager="ncurses on /usr/local"
+            cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+            has_curses=true
+	    cat >>confdefs.h <<\_ACEOF
+#define USE_NCURSES 1
+_ACEOF
+
+	fi
+    fi
+
+
+    if $search_ncurses
+    then
+        if test -f /usr/local/include/ncurses/ncurses.h
+	then
+	    echo "$as_me:$LINENO: result: Found ncurses on /usr/local/include/ncurses/ncurses.h" >&5
+echo "${ECHO_T}Found ncurses on /usr/local/include/ncurses/ncurses.h" >&6
+ 	    CURSES_LIBS="-L/usr/local/lib -L/usr/local/lib/ncurses -lncurses"
+	    CURSES_INCLUDEDIR="-I/usr/local/include/ncurses"
+	    search_ncurses=false
+	    screen_manager="ncurses on /usr/local/include/ncurses"
+            cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+            has_curses=true
+	    cat >>confdefs.h <<\_ACEOF
+#define USE_NCURSES 1
+_ACEOF
+
+	fi
+    fi
+
+
+
+    if $search_ncurses
+    then
+        if test -f /usr/local/include/ncurses/curses.h
+	then
+	    echo "$as_me:$LINENO: result: Found ncurses on /usr/local/include/ncurses/curses.h" >&5
+echo "${ECHO_T}Found ncurses on /usr/local/include/ncurses/curses.h" >&6
+ 	    CURSES_LIBS="-L/usr/local/lib -lncurses"
+	    CURSES_INCLUDEDIR="-I/usr/local/include/ncurses -DRENAMED_NCURSES"
+	    search_ncurses=false
+	    screen_manager="renamed ncurses on /usr/local/.../ncurses"
+            cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+            has_curses=true
+	    cat >>confdefs.h <<\_ACEOF
+#define USE_NCURSES 1
+_ACEOF
+
+	fi
+    fi
+
+
+
+    if $search_ncurses
+    then
+        if test -f /usr/include/ncurses/curses.h
+	then
+	    echo "$as_me:$LINENO: result: Found ncurses on /usr/include/ncurses/curses.h" >&5
+echo "${ECHO_T}Found ncurses on /usr/include/ncurses/curses.h" >&6
+ 	    CURSES_LIBS="-lncurses"
+	    CURSES_INCLUDEDIR="-I/usr/include/ncurses -DRENAMED_NCURSES"
+	    search_ncurses=false
+	    screen_manager="renamed ncurses on /usr/include/ncurses"
+            cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+            has_curses=true
+	    cat >>confdefs.h <<\_ACEOF
+#define USE_NCURSES 1
+_ACEOF
+
+	fi
+    fi
+
+
+                if $search_ncurses
+    then
+        cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include </usr/include/curses.h>
+
+_ACEOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  $EGREP "init_color" >/dev/null 2>&1; then
+
+	echo "$as_me:$LINENO: result: Using SysV curses" >&5
+echo "${ECHO_T}Using SysV curses" >&6
+	cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+	has_curses=true
+	cat >>confdefs.h <<\_ACEOF
+#define USE_SYSV_CURSES 1
+_ACEOF
+
+	search_ncurses=false
+	screen_manager="SysV/curses"
+	CURSES_LIBS="-lcurses"
+
+fi
+rm -f conftest*
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <curses.h>
+#ifdef __NCURSES_H
+#undef USE_NCURSES
+USE_NCURSES
+#endif
+
+_ACEOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  $EGREP "USE_NCURSES" >/dev/null 2>&1; then
+
+	CURSES_INCLUDEDIR="$CURSES_INCLUDEDIR -DRENAMED_NCURSES"
+        cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+	has_curses=true
+        cat >>confdefs.h <<\_ACEOF
+#define USE_NCURSES 1
+_ACEOF
+
+        search_ncurses=false
+        screen_manager="ncurses installed as curses"
+
+fi
+rm -f conftest*
+
+    fi
+
+                        if $search_ncurses
+    then
+	if test -f /usr/5include/curses.h
+	then
+
+	search_ncurses=false
+	screen_manager="SunOS 4.x /usr/5include curses"
+	echo "$as_me:$LINENO: result: Using SunOS 4.x /usr/5include curses" >&5
+echo "${ECHO_T}Using SunOS 4.x /usr/5include curses" >&6
+	cat >>confdefs.h <<\_ACEOF
+#define USE_SUNOS_CURSES 1
+_ACEOF
+
+	cat >>confdefs.h <<\_ACEOF
+#define HAS_CURSES 1
+_ACEOF
+
+	has_curses=true
+	cat >>confdefs.h <<\_ACEOF
+#define NO_COLOR_CURSES 1
+_ACEOF
+
+	cat >>confdefs.h <<\_ACEOF
+#define USE_SYSV_CURSES 1
+_ACEOF
+
+	CURSES_INCLUDEDIR="-I/usr/5include"
+	CURSES_LIBS="/usr/5lib/libcurses.a /usr/5lib/libtermcap.a"
+	echo "$as_me:$LINENO: result: Please note that some screen refreshs may fail" >&5
+echo "${ECHO_T}Please note that some screen refreshs may fail" >&6
+
+        fi
+    else
+        # check for ncurses version, to properly ifdef mouse-fix
+	echo "$as_me:$LINENO: checking for ncurses version" >&5
+echo $ECHO_N "checking for ncurses version... $ECHO_C" >&6
+	ncurses_version=unknown
+cat > conftest.$ac_ext <<EOF
+#line 4959 "configure"
+#include "confdefs.h"
+#ifdef RENAMED_NCURSES
+#include <curses.h>
+#else
+#include <ncurses.h>
+#endif
+#undef VERSION
+VERSION:NCURSES_VERSION
+EOF
+        if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  egrep "VERSION:" >conftest.out 2>&1; then
+            ncurses_version=`cat conftest.out|sed -e 's/^[^"]*"//' -e 's/".*//'`
+	fi
+	rm -rf conftest*
+        echo "$as_me:$LINENO: result: $ncurses_version" >&5
+echo "${ECHO_T}$ncurses_version" >&6
+	case "$ncurses_version" in
+	4.[01])
+            cat >>confdefs.h <<\_ACEOF
+#define NCURSES_970530 2
+_ACEOF
+
+            ;;
+	1.9.9g)
+            cat >>confdefs.h <<\_ACEOF
+#define NCURSES_970530 1
+_ACEOF
+
+            ;;
+	1*)
+            cat >>confdefs.h <<\_ACEOF
+#define NCURSES_970530 0
+_ACEOF
+
+            ;;
+	esac
+    fi
+
+	fi
+
+
+
+
+        if test "x$has_curses" != "xtrue"
+        then
+                if test "x$ui" = "xcurses"
+                then
+                        { { echo "$as_me:$LINENO: error:
+The chosen UI (curses) is unconfigurable.
+The appropriate libraries could not be found.
+                        " >&5
+echo "$as_me: error:
+The chosen UI (curses) is unconfigurable.
+The appropriate libraries could not be found.
+                        " >&2;}
+   { (exit 1); exit 1; }; }
+                fi
+        else
+                UI_CFLAGS=$CURSES_INCLUDEDIR
+                UI_CPPFLAGS=
+                UI_CXXFLAGS=
+                UI_LIBS=$CURSES_LIBS
+                UI_LDFLAGS=
+                UI_DIR=ui-curses
+                found_ui=yes
+                ui=curses
+                { echo "$as_me:$LINENO: Using curses UI" >&5
+echo "$as_me: Using curses UI" >&6;}
+        fi
+fi
+
+if test "x$found_ui" = "xno"
+then
+        { { echo "$as_me:$LINENO: error: Couldn't find a working UI." >&5
+echo "$as_me: error: Couldn't find a working UI." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
+
+
+
+
+
+
+if test "x$ui" = "xdumb"; then
+  UI_DUMB_TRUE=
+  UI_DUMB_FALSE='#'
+else
+  UI_DUMB_TRUE='#'
+  UI_DUMB_FALSE=
+fi
+
+
+
+# Checks for header files.
 echo "$as_me:$LINENO: checking for ANSI C header files" >&5
 echo $ECHO_N "checking for ANSI C header files... $ECHO_C" >&6
 if test "${ac_cv_header_stdc+set}" = set; then
@@ -6659,6 +7194,7 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
+  "src/ui-curses/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/ui-curses/Makefile" ;;
   "src/ui-dumb/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/ui-dumb/Makefile" ;;
   "src/ui-wx/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/ui-wx/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
@@ -6815,6 +7351,10 @@ s,@WX_CXXFLAGS_ONLY@,$WX_CXXFLAGS_ONLY,;t t
 s,@WX_LIBS@,$WX_LIBS,;t t
 s,@WX_LIBS_STATIC@,$WX_LIBS_STATIC,;t t
 s,@WX_VERSION@,$WX_VERSION,;t t
+s,@CURSES_LIBS@,$CURSES_LIBS,;t t
+s,@CURSES_INCLUDEDIR@,$CURSES_INCLUDEDIR,;t t
+s,@CPP@,$CPP,;t t
+s,@EGREP@,$EGREP,;t t
 s,@UI_CFLAGS@,$UI_CFLAGS,;t t
 s,@UI_CPPFLAGS@,$UI_CPPFLAGS,;t t
 s,@UI_CXXFLAGS@,$UI_CXXFLAGS,;t t
@@ -6823,8 +7363,6 @@ s,@UI_LDFLAGS@,$UI_LDFLAGS,;t t
 s,@UI_DIR@,$UI_DIR,;t t
 s,@UI_DUMB_TRUE@,$UI_DUMB_TRUE,;t t
 s,@UI_DUMB_FALSE@,$UI_DUMB_FALSE,;t t
-s,@CPP@,$CPP,;t t
-s,@EGREP@,$EGREP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
