Modularizing encryption.
git-svn-id: svn://svn.code.sf.net/p/directnet/code/trunk@100 40aaf297-f90e-0410-8da6-8adc2782f1e2

diff --git a/directnet/configure b/directnet/configure
--- a/directnet/configure
+++ b/directnet/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB build build_cpu build_vendor build_os host host_cpu host_vendor host_os acx_pthread_config PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS WX_CONFIG_PATH WX_CPPFLAGS WX_CFLAGS WX_CXXFLAGS WX_CFLAGS_ONLY WX_CXXFLAGS_ONLY WX_LIBS WX_LIBS_STATIC WX_VERSION CURSES_LIBS CURSES_INCLUDEDIR EGREP READLINE_LIBS READLINE_INCLUDES UI_CFLAGS UI_CPPFLAGS UI_CXXFLAGS UI_LIBS UI_LDFLAGS UI_DIR UI_CXX_TRUE UI_CXX_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB build build_cpu build_vendor build_os host host_cpu host_vendor host_os acx_pthread_config PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS WX_CONFIG_PATH WX_CPPFLAGS WX_CFLAGS WX_CXXFLAGS WX_CFLAGS_ONLY WX_CXXFLAGS_ONLY WX_LIBS WX_LIBS_STATIC WX_VERSION CURSES_LIBS CURSES_INCLUDEDIR EGREP READLINE_LIBS READLINE_INCLUDES UI_CFLAGS UI_CPPFLAGS UI_CXXFLAGS UI_LIBS UI_LDFLAGS UI_DIR UI_CXX_TRUE UI_CXX_FALSE ENC_CFLAGS ENC_CPPFLAGS ENC_CXXFLAGS ENC_LIBS ENC_LDFLAGS ENC_DIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -865,6 +865,8 @@ Optional Features:
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-ui=dumb
                 set the UI (currently the only UI is "dumb")
+  --enable-enc=fake
+                set the encryption (currently the only encryption is "fake")
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -5182,7 +5184,7 @@ echo "${ECHO_T}Please note that some screen refreshs may fail" >&6
 echo $ECHO_N "checking for ncurses version... $ECHO_C" >&6
 	ncurses_version=unknown
 cat > conftest.$ac_ext <<EOF
-#line 5185 "configure"
+#line 5187 "configure"
 #include "confdefs.h"
 #ifdef RENAMED_NCURSES
 #include <curses.h>
@@ -5402,6 +5404,71 @@ else
   UI_CXX_TRUE='#'
   UI_CXX_FALSE=
 fi
+
+
+
+# Check for encryption to use
+# Check whether --enable-enc or --disable-enc was given.
+if test "${enable_enc+set}" = set; then
+  enableval="$enable_enc"
+  case "$enableval" in
+        fake) enc=fake ;;
+        gpg) enc=gpg ;;
+        *) { { echo "$as_me:$LINENO: error: Invalid encryption chosen." >&5
+echo "$as_me: error: Invalid encryption chosen." >&2;}
+   { (exit 1); exit 1; }; } ;;
+esac
+else
+  enc=determine
+fi;
+
+{ echo "$as_me:$LINENO: checking which encryption to use..." >&5
+echo "$as_me: checking which encryption to use..." >&6;}
+
+found_enc=no
+
+if test "x$enc" = "xfake" || test "x$enc" = "xdetermine"
+then
+        ENC_CFLAGS=
+        ENC_CPPFLAGS=
+        ENC_CXXFLAGS=
+        ENC_CXX=false
+        ENC_LIBS=
+        ENC_LDFLAGS=
+        ENC_DIR=enc-fake
+        found_enc=yes
+        enc=fake
+        { echo "$as_me:$LINENO: Using fake encryption" >&5
+echo "$as_me: Using fake encryption" >&6;}
+fi
+
+if test "x$enc" = "xgpg" || ( test "x$enc" = "xdetermine" && test "x$found_enc" = "xno" )
+then
+        ENC_CFLAGS=
+        ENC_CPPFLAGS=
+        ENC_CXXFLAGS=
+        ENC_CXX=false
+        ENC_LIBS=
+        ENC_LDFLAGS=
+        ENC_DIR=enc-gpg
+        found_enc=yes
+        enc=gpg
+        { echo "$as_me:$LINENO: Using GPG encryption" >&5
+echo "$as_me: Using GPG encryption" >&6;}
+fi
+
+if test "x$found_enc" = "xno"
+then
+        { { echo "$as_me:$LINENO: error: Couldn't find a working encryption library." >&5
+echo "$as_me: error: Couldn't find a working encryption library." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
+
+
+
 
 
 
@@ -7717,6 +7784,12 @@ s,@UI_LDFLAGS@,$UI_LDFLAGS,;t t
 s,@UI_DIR@,$UI_DIR,;t t
 s,@UI_CXX_TRUE@,$UI_CXX_TRUE,;t t
 s,@UI_CXX_FALSE@,$UI_CXX_FALSE,;t t
+s,@ENC_CFLAGS@,$ENC_CFLAGS,;t t
+s,@ENC_CPPFLAGS@,$ENC_CPPFLAGS,;t t
+s,@ENC_CXXFLAGS@,$ENC_CXXFLAGS,;t t
+s,@ENC_LIBS@,$ENC_LIBS,;t t
+s,@ENC_LDFLAGS@,$ENC_LDFLAGS,;t t
+s,@ENC_DIR@,$ENC_DIR,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
